# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'reko' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for reko
  pod 'Alamofire'
  pod 'QRCodeGenerator'
  pod 'Socket.IO-Client-Swift', '~> 13.3.0'
  pod 'SwiftyJSON'

  target 'rekoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
